Use vcpkg submodule

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,18 +27,16 @@ jobs:
           - os: ubuntu-latest
             preset: clang-debug
     runs-on: ${{ matrix.os }}
-    env:
-      CMAKE_COMPILE_WARNING_AS_ERROR: "ON"
     steps:
       - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+        with:
+          submodules: true
       # Set up x64 developer command prompt on Windows
-      # Important: this must be done before run-vcpkg because both set VCPKG_ROOT and we want run-vcpkg's
       - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
         if: runner.os == 'Windows'
         with:
           arch: x64
       - uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb # v4.4.2
-      - uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
       - run: cmake --workflow --preset ${{ matrix.preset }}
       - run: |
           if [ -n "$(git status --porcelain)" ]; then
@@ -52,8 +50,17 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+        with:
+          submodules: true
+      - run: |
+          # Ensure "builtin-baseline" in vcpkg.json is the same as the vcpkg submodule commit hash
+          BUILTIN_BASELINE=`node -p "require('./vcpkg.json')['builtin-baseline']"`
+          COMMIT_HASH=`git -C vcpkg rev-parse HEAD`
+          if [[ "$BUILTIN_BASELINE" != "$COMMIT_HASH" ]]; then
+            echo "::error::builtin-baseline in vcpkg.json does not match vcpkg submodule commit hash ($BUILTIN_BASELINE != $COMMIT_HASH)!"
+            exit 1
+          fi
       - uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb # v4.4.2
-      - uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
       - run: cmake --preset clang-debug
       # TODO: Run clang-tidy with pinned version
 
